branches: master
repositoryUrl: https://github.com/liatrio/image-atlantis.git
plugins:
  - @semantic-release/commit-analyzer
  - @semantic-release/release-notes-generator
  - @semantic-release/github
