# This is a basic workflow to help you get started with Actions

name: Build, Scan, Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        uses: liatrio/github-actions/conventional-release@master
        with:
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Release Tag
        id: tag
        run: |
          echo ::set-output name=newVersion::$(git tag --points-at HEAD)

    outputs:
      newVersion: ${{ steps.tag.outputs.newVersion }}

  tag:
    needs: release
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
     - name: Set default tag
       if: ${{ needs.release.status != 'success' }}
       run: echo "IMAGE_TAG=local" >> $GITHUB_ENV

     - name: Set version tag
       if: ${{ needs.release.status == 'success' }}
       run: echo "IMAGE_TAG=${{ needs.release.outputs.newVersion }}" >> $GITHUB_ENV
    outputs:
      imageTag: ${{ env.IMAGE_TAG }}

  build:
    needs: tag
    if: ${{ always() }}
    uses: liatrio/github-workflows/.github/workflows/build-scan-push.yaml@build-push-typo
    with:
      publish: ${{ github.ref == 'refs/heads/main' }}
      repository: ghcr.io/liatrio
      registry-username: ${{ github.repository_owner }}
      tag: ${{ needs.tag.outputs.imageTag }}
      image-name: ${{ github.event.repository.name }}
      nofail: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
