# This is a basic workflow to help you get started with Actions

name: Build, Scan, Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        uses: liatrio/github-actions/conventional-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      changed: ${{ steps.Release.outputs.changed }}
      newVersion: ${{ steps.Release.outputs.newVersion }}

  build:
    needs: release
    if: ${{ needs.release.outputs.changed }} == "true"
    uses: liatrio/github-workflows/.github/workflows/build-scan-push.yaml@main
    with:
      publish: ${{ github.ref == 'refs/heads/master' }}
      repository: ghcr.io/liatrio
      registry-username: ${{ github.repository_owner }}
      tag: ${{ needs.release.outputs.newVersion }}
      image-name: ${{ github.event.repository.name }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
